# Generated by Django 4.1.2 on 2022-10-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('cpassword', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
