# Generated by Django 4.1.2 on 2022-10-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='Name',
            field=models.CharField(default='savings', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_balance',
            field=models.IntegerField(default=1000),
        ),
    ]
