# Generated by Django 4.1.2 on 2022-10-15 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankingSystem', '0003_alter_accounttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type_id',
            field=models.OneToOneField(default='savings', on_delete=django.db.models.deletion.CASCADE, to='BankingSystem.accounttype'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
