# Generated by Django 4.1.2 on 2022-10-15 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankingSystem', '0006_alter_profile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type_id',
            field=models.ForeignKey(default='savings', on_delete=django.db.models.deletion.CASCADE, to='BankingSystem.accounttype'),
        ),
    ]
